
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
  sh "flutter clean"
  sh "flutter build apk --release --target lib/main.dart"
      firebase_app_distribution(
        app: "1:363769471097:android:c09e5440786882ba4234a8",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        groups: "qa-team, trusted-testers",
        android_artifact_type:"APK",
        android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
        testers:"hibachamkhi12@gmail.com",
        release_notes:"First Fastlane Distribution"
      )
  end
end
